/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizshowIndexRouteImport } from './routes/quizshow/index'
import { Route as ChatUiSampleRouteImport } from './routes/chat/ui-sample'
import { Route as ChatTtsRouteImport } from './routes/chat/tts'
import { Route as ChatPersistenceRouteImport } from './routes/chat/persistence'
import { Route as ChatImageRouteImport } from './routes/chat/image'
import { Route as ChatCustomGptRouteImport } from './routes/chat/custom-gpt'
import { Route as ChatBasicRouteImport } from './routes/chat/basic'
import { Route as BuzzerConnectRouteImport } from './routes/buzzer/connect'
import { Route as BuzzerBuzzerRouteImport } from './routes/buzzer/buzzer'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiQuizshowRouteImport } from './routes/api/quizshow'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiCustomGptRouteImport } from './routes/api/custom-gpt'
import { Route as ApiChatWithToolsRouteImport } from './routes/api/chat-with-tools'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizshowIndexRoute = QuizshowIndexRouteImport.update({
  id: '/quizshow/',
  path: '/quizshow/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUiSampleRoute = ChatUiSampleRouteImport.update({
  id: '/chat/ui-sample',
  path: '/chat/ui-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatTtsRoute = ChatTtsRouteImport.update({
  id: '/chat/tts',
  path: '/chat/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPersistenceRoute = ChatPersistenceRouteImport.update({
  id: '/chat/persistence',
  path: '/chat/persistence',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatImageRoute = ChatImageRouteImport.update({
  id: '/chat/image',
  path: '/chat/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCustomGptRoute = ChatCustomGptRouteImport.update({
  id: '/chat/custom-gpt',
  path: '/chat/custom-gpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBasicRoute = ChatBasicRouteImport.update({
  id: '/chat/basic',
  path: '/chat/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const BuzzerConnectRoute = BuzzerConnectRouteImport.update({
  id: '/buzzer/connect',
  path: '/buzzer/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BuzzerBuzzerRoute = BuzzerBuzzerRouteImport.update({
  id: '/buzzer/buzzer',
  path: '/buzzer/buzzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizshowRoute = ApiQuizshowRouteImport.update({
  id: '/api/quizshow',
  path: '/api/quizshow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomGptRoute = ApiCustomGptRouteImport.update({
  id: '/api/custom-gpt',
  path: '/api/custom-gpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatWithToolsRoute = ApiChatWithToolsRouteImport.update({
  id: '/api/chat-with-tools',
  path: '/api/chat-with-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer/buzzer': typeof BuzzerBuzzerRoute
  '/buzzer/connect': typeof BuzzerConnectRoute
  '/chat/basic': typeof ChatBasicRoute
  '/chat/custom-gpt': typeof ChatCustomGptRoute
  '/chat/image': typeof ChatImageRoute
  '/chat/persistence': typeof ChatPersistenceRoute
  '/chat/tts': typeof ChatTtsRoute
  '/chat/ui-sample': typeof ChatUiSampleRoute
  '/quizshow': typeof QuizshowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer/buzzer': typeof BuzzerBuzzerRoute
  '/buzzer/connect': typeof BuzzerConnectRoute
  '/chat/basic': typeof ChatBasicRoute
  '/chat/custom-gpt': typeof ChatCustomGptRoute
  '/chat/image': typeof ChatImageRoute
  '/chat/persistence': typeof ChatPersistenceRoute
  '/chat/tts': typeof ChatTtsRoute
  '/chat/ui-sample': typeof ChatUiSampleRoute
  '/quizshow': typeof QuizshowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer/buzzer': typeof BuzzerBuzzerRoute
  '/buzzer/connect': typeof BuzzerConnectRoute
  '/chat/basic': typeof ChatBasicRoute
  '/chat/custom-gpt': typeof ChatCustomGptRoute
  '/chat/image': typeof ChatImageRoute
  '/chat/persistence': typeof ChatPersistenceRoute
  '/chat/tts': typeof ChatTtsRoute
  '/chat/ui-sample': typeof ChatUiSampleRoute
  '/quizshow/': typeof QuizshowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/summarize'
    | '/buzzer/buzzer'
    | '/buzzer/connect'
    | '/chat/basic'
    | '/chat/custom-gpt'
    | '/chat/image'
    | '/chat/persistence'
    | '/chat/tts'
    | '/chat/ui-sample'
    | '/quizshow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/summarize'
    | '/buzzer/buzzer'
    | '/buzzer/connect'
    | '/chat/basic'
    | '/chat/custom-gpt'
    | '/chat/image'
    | '/chat/persistence'
    | '/chat/tts'
    | '/chat/ui-sample'
    | '/quizshow'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/summarize'
    | '/buzzer/buzzer'
    | '/buzzer/connect'
    | '/chat/basic'
    | '/chat/custom-gpt'
    | '/chat/image'
    | '/chat/persistence'
    | '/chat/tts'
    | '/chat/ui-sample'
    | '/quizshow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatWithToolsRoute: typeof ApiChatWithToolsRoute
  ApiCustomGptRoute: typeof ApiCustomGptRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiQuizshowRoute: typeof ApiQuizshowRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  BuzzerBuzzerRoute: typeof BuzzerBuzzerRoute
  BuzzerConnectRoute: typeof BuzzerConnectRoute
  ChatBasicRoute: typeof ChatBasicRoute
  ChatCustomGptRoute: typeof ChatCustomGptRoute
  ChatImageRoute: typeof ChatImageRoute
  ChatPersistenceRoute: typeof ChatPersistenceRoute
  ChatTtsRoute: typeof ChatTtsRoute
  ChatUiSampleRoute: typeof ChatUiSampleRoute
  QuizshowIndexRoute: typeof QuizshowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizshow/': {
      id: '/quizshow/'
      path: '/quizshow'
      fullPath: '/quizshow'
      preLoaderRoute: typeof QuizshowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/ui-sample': {
      id: '/chat/ui-sample'
      path: '/chat/ui-sample'
      fullPath: '/chat/ui-sample'
      preLoaderRoute: typeof ChatUiSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/tts': {
      id: '/chat/tts'
      path: '/chat/tts'
      fullPath: '/chat/tts'
      preLoaderRoute: typeof ChatTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/persistence': {
      id: '/chat/persistence'
      path: '/chat/persistence'
      fullPath: '/chat/persistence'
      preLoaderRoute: typeof ChatPersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/image': {
      id: '/chat/image'
      path: '/chat/image'
      fullPath: '/chat/image'
      preLoaderRoute: typeof ChatImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/custom-gpt': {
      id: '/chat/custom-gpt'
      path: '/chat/custom-gpt'
      fullPath: '/chat/custom-gpt'
      preLoaderRoute: typeof ChatCustomGptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/basic': {
      id: '/chat/basic'
      path: '/chat/basic'
      fullPath: '/chat/basic'
      preLoaderRoute: typeof ChatBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buzzer/connect': {
      id: '/buzzer/connect'
      path: '/buzzer/connect'
      fullPath: '/buzzer/connect'
      preLoaderRoute: typeof BuzzerConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buzzer/buzzer': {
      id: '/buzzer/buzzer'
      path: '/buzzer/buzzer'
      fullPath: '/buzzer/buzzer'
      preLoaderRoute: typeof BuzzerBuzzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizshow': {
      id: '/api/quizshow'
      path: '/api/quizshow'
      fullPath: '/api/quizshow'
      preLoaderRoute: typeof ApiQuizshowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/custom-gpt': {
      id: '/api/custom-gpt'
      path: '/api/custom-gpt'
      fullPath: '/api/custom-gpt'
      preLoaderRoute: typeof ApiCustomGptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-with-tools': {
      id: '/api/chat-with-tools'
      path: '/api/chat-with-tools'
      fullPath: '/api/chat-with-tools'
      preLoaderRoute: typeof ApiChatWithToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatWithToolsRoute: ApiChatWithToolsRoute,
  ApiCustomGptRoute: ApiCustomGptRoute,
  ApiImageRoute: ApiImageRoute,
  ApiQuizshowRoute: ApiQuizshowRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  BuzzerBuzzerRoute: BuzzerBuzzerRoute,
  BuzzerConnectRoute: BuzzerConnectRoute,
  ChatBasicRoute: ChatBasicRoute,
  ChatCustomGptRoute: ChatCustomGptRoute,
  ChatImageRoute: ChatImageRoute,
  ChatPersistenceRoute: ChatPersistenceRoute,
  ChatTtsRoute: ChatTtsRoute,
  ChatUiSampleRoute: ChatUiSampleRoute,
  QuizshowIndexRoute: QuizshowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
