/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizshowIndexRouteImport } from './routes/quizshow/index'
import { Route as ImageIndexRouteImport } from './routes/image/index'
import { Route as ChatUiSampleIndexRouteImport } from './routes/chat-ui-sample/index'
import { Route as ChatTtsIndexRouteImport } from './routes/chat-tts/index'
import { Route as ChatPersistenceIndexRouteImport } from './routes/chat-persistence/index'
import { Route as ChatCustomGptIndexRouteImport } from './routes/chat-custom-gpt/index'
import { Route as ChatBasicIndexRouteImport } from './routes/chat-basic/index'
import { Route as BuzzerIndexRouteImport } from './routes/buzzer/index'
import { Route as BuzzerConnectIndexRouteImport } from './routes/buzzer-connect/index'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiSocketRouteImport } from './routes/api/socket'
import { Route as ApiQuizshowRouteImport } from './routes/api/quizshow'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiCustomGptRouteImport } from './routes/api/custom-gpt'
import { Route as ApiChatWithToolsRouteImport } from './routes/api/chat-with-tools'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizshowIndexRoute = QuizshowIndexRouteImport.update({
  id: '/quizshow/',
  path: '/quizshow/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageIndexRoute = ImageIndexRouteImport.update({
  id: '/image/',
  path: '/image/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUiSampleIndexRoute = ChatUiSampleIndexRouteImport.update({
  id: '/chat-ui-sample/',
  path: '/chat-ui-sample/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatTtsIndexRoute = ChatTtsIndexRouteImport.update({
  id: '/chat-tts/',
  path: '/chat-tts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPersistenceIndexRoute = ChatPersistenceIndexRouteImport.update({
  id: '/chat-persistence/',
  path: '/chat-persistence/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCustomGptIndexRoute = ChatCustomGptIndexRouteImport.update({
  id: '/chat-custom-gpt/',
  path: '/chat-custom-gpt/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBasicIndexRoute = ChatBasicIndexRouteImport.update({
  id: '/chat-basic/',
  path: '/chat-basic/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuzzerIndexRoute = BuzzerIndexRouteImport.update({
  id: '/buzzer/',
  path: '/buzzer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuzzerConnectIndexRoute = BuzzerConnectIndexRouteImport.update({
  id: '/buzzer-connect/',
  path: '/buzzer-connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocketRoute = ApiSocketRouteImport.update({
  id: '/api/socket',
  path: '/api/socket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizshowRoute = ApiQuizshowRouteImport.update({
  id: '/api/quizshow',
  path: '/api/quizshow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomGptRoute = ApiCustomGptRouteImport.update({
  id: '/api/custom-gpt',
  path: '/api/custom-gpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatWithToolsRoute = ApiChatWithToolsRouteImport.update({
  id: '/api/chat-with-tools',
  path: '/api/chat-with-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/socket': typeof ApiSocketRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer-connect': typeof BuzzerConnectIndexRoute
  '/buzzer': typeof BuzzerIndexRoute
  '/chat-basic': typeof ChatBasicIndexRoute
  '/chat-custom-gpt': typeof ChatCustomGptIndexRoute
  '/chat-persistence': typeof ChatPersistenceIndexRoute
  '/chat-tts': typeof ChatTtsIndexRoute
  '/chat-ui-sample': typeof ChatUiSampleIndexRoute
  '/image': typeof ImageIndexRoute
  '/quizshow': typeof QuizshowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/socket': typeof ApiSocketRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer-connect': typeof BuzzerConnectIndexRoute
  '/buzzer': typeof BuzzerIndexRoute
  '/chat-basic': typeof ChatBasicIndexRoute
  '/chat-custom-gpt': typeof ChatCustomGptIndexRoute
  '/chat-persistence': typeof ChatPersistenceIndexRoute
  '/chat-tts': typeof ChatTtsIndexRoute
  '/chat-ui-sample': typeof ChatUiSampleIndexRoute
  '/image': typeof ImageIndexRoute
  '/quizshow': typeof QuizshowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-with-tools': typeof ApiChatWithToolsRoute
  '/api/custom-gpt': typeof ApiCustomGptRoute
  '/api/image': typeof ApiImageRoute
  '/api/quizshow': typeof ApiQuizshowRoute
  '/api/socket': typeof ApiSocketRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/buzzer-connect/': typeof BuzzerConnectIndexRoute
  '/buzzer/': typeof BuzzerIndexRoute
  '/chat-basic/': typeof ChatBasicIndexRoute
  '/chat-custom-gpt/': typeof ChatCustomGptIndexRoute
  '/chat-persistence/': typeof ChatPersistenceIndexRoute
  '/chat-tts/': typeof ChatTtsIndexRoute
  '/chat-ui-sample/': typeof ChatUiSampleIndexRoute
  '/image/': typeof ImageIndexRoute
  '/quizshow/': typeof QuizshowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/socket'
    | '/api/summarize'
    | '/buzzer-connect'
    | '/buzzer'
    | '/chat-basic'
    | '/chat-custom-gpt'
    | '/chat-persistence'
    | '/chat-tts'
    | '/chat-ui-sample'
    | '/image'
    | '/quizshow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/socket'
    | '/api/summarize'
    | '/buzzer-connect'
    | '/buzzer'
    | '/chat-basic'
    | '/chat-custom-gpt'
    | '/chat-persistence'
    | '/chat-tts'
    | '/chat-ui-sample'
    | '/image'
    | '/quizshow'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat-with-tools'
    | '/api/custom-gpt'
    | '/api/image'
    | '/api/quizshow'
    | '/api/socket'
    | '/api/summarize'
    | '/buzzer-connect/'
    | '/buzzer/'
    | '/chat-basic/'
    | '/chat-custom-gpt/'
    | '/chat-persistence/'
    | '/chat-tts/'
    | '/chat-ui-sample/'
    | '/image/'
    | '/quizshow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatWithToolsRoute: typeof ApiChatWithToolsRoute
  ApiCustomGptRoute: typeof ApiCustomGptRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiQuizshowRoute: typeof ApiQuizshowRoute
  ApiSocketRoute: typeof ApiSocketRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  BuzzerConnectIndexRoute: typeof BuzzerConnectIndexRoute
  BuzzerIndexRoute: typeof BuzzerIndexRoute
  ChatBasicIndexRoute: typeof ChatBasicIndexRoute
  ChatCustomGptIndexRoute: typeof ChatCustomGptIndexRoute
  ChatPersistenceIndexRoute: typeof ChatPersistenceIndexRoute
  ChatTtsIndexRoute: typeof ChatTtsIndexRoute
  ChatUiSampleIndexRoute: typeof ChatUiSampleIndexRoute
  ImageIndexRoute: typeof ImageIndexRoute
  QuizshowIndexRoute: typeof QuizshowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizshow/': {
      id: '/quizshow/'
      path: '/quizshow'
      fullPath: '/quizshow'
      preLoaderRoute: typeof QuizshowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/': {
      id: '/image/'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-ui-sample/': {
      id: '/chat-ui-sample/'
      path: '/chat-ui-sample'
      fullPath: '/chat-ui-sample'
      preLoaderRoute: typeof ChatUiSampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-tts/': {
      id: '/chat-tts/'
      path: '/chat-tts'
      fullPath: '/chat-tts'
      preLoaderRoute: typeof ChatTtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-persistence/': {
      id: '/chat-persistence/'
      path: '/chat-persistence'
      fullPath: '/chat-persistence'
      preLoaderRoute: typeof ChatPersistenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-custom-gpt/': {
      id: '/chat-custom-gpt/'
      path: '/chat-custom-gpt'
      fullPath: '/chat-custom-gpt'
      preLoaderRoute: typeof ChatCustomGptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-basic/': {
      id: '/chat-basic/'
      path: '/chat-basic'
      fullPath: '/chat-basic'
      preLoaderRoute: typeof ChatBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buzzer/': {
      id: '/buzzer/'
      path: '/buzzer'
      fullPath: '/buzzer'
      preLoaderRoute: typeof BuzzerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buzzer-connect/': {
      id: '/buzzer-connect/'
      path: '/buzzer-connect'
      fullPath: '/buzzer-connect'
      preLoaderRoute: typeof BuzzerConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/socket': {
      id: '/api/socket'
      path: '/api/socket'
      fullPath: '/api/socket'
      preLoaderRoute: typeof ApiSocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizshow': {
      id: '/api/quizshow'
      path: '/api/quizshow'
      fullPath: '/api/quizshow'
      preLoaderRoute: typeof ApiQuizshowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/custom-gpt': {
      id: '/api/custom-gpt'
      path: '/api/custom-gpt'
      fullPath: '/api/custom-gpt'
      preLoaderRoute: typeof ApiCustomGptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-with-tools': {
      id: '/api/chat-with-tools'
      path: '/api/chat-with-tools'
      fullPath: '/api/chat-with-tools'
      preLoaderRoute: typeof ApiChatWithToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatWithToolsRoute: ApiChatWithToolsRoute,
  ApiCustomGptRoute: ApiCustomGptRoute,
  ApiImageRoute: ApiImageRoute,
  ApiQuizshowRoute: ApiQuizshowRoute,
  ApiSocketRoute: ApiSocketRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  BuzzerConnectIndexRoute: BuzzerConnectIndexRoute,
  BuzzerIndexRoute: BuzzerIndexRoute,
  ChatBasicIndexRoute: ChatBasicIndexRoute,
  ChatCustomGptIndexRoute: ChatCustomGptIndexRoute,
  ChatPersistenceIndexRoute: ChatPersistenceIndexRoute,
  ChatTtsIndexRoute: ChatTtsIndexRoute,
  ChatUiSampleIndexRoute: ChatUiSampleIndexRoute,
  ImageIndexRoute: ImageIndexRoute,
  QuizshowIndexRoute: QuizshowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
